name: Python Flask App Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v3

    - name: 🐍 Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 📦 Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: ✅ Run app check
      run: |
        python app.py --help || true  # Make sure app.py is runnable

    # Optional: Add test step if you have tests
    # - name: 🧪 Run tests
    #   run: |
    #     pytest  # or another test command
