name: Python Flask App Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 12 * * 0" # Runs weekly (Sunday 12:00 UTC)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v3

    - name: 🐍 Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 📦 Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: ✅ Check Python app (Import Test)
      id: check_app
      run: |
        if python -c "import app"; then
          echo "status=success" >> $GITHUB_OUTPUT
        else
          echo "status=failure" >> $GITHUB_OUTPUT
        fi

    - name: 📝 Update README with status
      run: |
        STATUS="${{ steps.check_app.outputs.status }}"
        DATE=$(date '+%B %d, %Y')
        if [[ "$STATUS" == "success" ]]; then
          BADGE="✅ Successful"
        else
          BADGE="❌ Failed"
        fi
        sed -i '/^Last Run:/c\Last Run: '"$BADGE"' on '"$DATE" README.md || echo "Last Run: $BADGE on $DATE" >> README.md

    - name: 🤝 Update Contributors Section
      uses: akhilmhdh/contributors-readme-action@v2.3.6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        image_size: 100
        columns_per_row: 6
        commit_message: "🤝 Auto-update contributors list"

    - name: 🚀 Commit changes to README
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "📄 Update README with latest run status and contributors"
